"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.models  # noqa: F401  (UTCDateTime type)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=300), nullable=True),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False)

    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legal_name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("trading_name", sa.String(length=300), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column(
            "industry_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("estimated_employee_min", sa.Integer(), nullable=True),
        sa.Column("estimated_employee_max", sa.Integer(), nullable=True),
        sa.Column("revenue_min", sa.Integer(), nullable=True),
        sa.Column("revenue_max", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("ownership_type", sa.String(length=32), nullable=False),
        sa.Column("qualification_status", sa.String(length=32), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("merged_into_id", sa.String(length=36), nullable=True),
        sa.Column("first_seen_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("last_verified_at", app.models.UTCDateTime(), nullable=True),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_country"), ["country"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_normalized_name"), ["normalized_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_companies_qualification_status"), ["qualification_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_companies_review_status"), ["review_status"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_sector"), ["sector"], unique=False)

    op.create_table(
        "contact_suppressions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("request_reference", sa.String(length=200), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_hash"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column(
            "countries",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_mode", sa.String(length=32), nullable=False),
        sa.Column("terms_url", sa.String(length=500), nullable=True),
        sa.Column("permission_status", sa.String(length=32), nullable=False),
        sa.Column("approval_reference", sa.String(length=300), nullable=True),
        sa.Column("connector_type", sa.String(length=32), nullable=False),
        sa.Column(
            "connector_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "allowed_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "field_mapping",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("base_confidence", sa.String(length=32), nullable=False),
        sa.Column("usage_policy", sa.String(length=64), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column("trust_rank", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_identifiers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=300), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("derived", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "value", name="uq_identifier_kind_value"),
    )
    with op.batch_alter_table("company_identifiers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_company_identifiers_company_id"), ["company_id"], unique=False)

    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_a_id", sa.String(length=36), nullable=False),
        sa.Column("company_b_id", sa.String(length=36), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resolved_by", sa.String(length=200), nullable=True),
        sa.Column("resolved_at", app.models.UTCDateTime(), nullable=True),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_a_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_b_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_a_id", "company_b_id", name="uq_duplicate_pair"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("file_name", sa.String(length=300), nullable=True),
        sa.Column(
            "query",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("region", sa.String(length=32), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("input_text", sa.Text(), nullable=True),
        sa.Column("input_expires_at", app.models.UTCDateTime(), nullable=True),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("min_employees", sa.Integer(), nullable=False),
        sa.Column(
            "counts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "errors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("retry_of_id", sa.String(length=36), nullable=True),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("started_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("finished_at", app.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["retry_of_id"],
            ["ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("profile_url", sa.String(length=500), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("contact_basis", sa.String(length=32), nullable=False),
        sa.Column("usage_policy", sa.String(length=64), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("last_verified_at", app.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contacts_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_identity_hash"), ["identity_hash"], unique=False)

    op.create_table(
        "ingestion_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=300), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("qualification", sa.String(length=32), nullable=True),
        sa.Column(
            "match_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "errors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["ingestion_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingestion_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingestion_records_run_id"), ["run_id"], unique=False)

    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("source_key", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=200), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("retrieved_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("expires_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("expired_at", app.models.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_key", "content_hash", name="uq_snapshot_identity"),
    )
    op.create_table(
        "company_facts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column(
            "value_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("value_hash", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("valid_from", app.models.UTCDateTime(), nullable=False),
        sa.Column("valid_to", app.models.UTCDateTime(), nullable=True),
        sa.Column("base_confidence", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("usage_policy", sa.String(length=64), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("reviewed_at", app.models.UTCDateTime(), nullable=True),
        sa.Column("is_correction", sa.Boolean(), nullable=False),
        sa.Column("corrects_fact_id", sa.String(length=36), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["corrects_fact_id"],
            ["company_facts.id"],
        ),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["source_snapshots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_facts", schema=None) as batch_op:
        batch_op.create_index("ix_fact_company_field", ["company_id", "field_name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_facts", schema=None) as batch_op:
        batch_op.drop_index("ix_fact_company_field")

    op.drop_table("company_facts")
    op.drop_table("source_snapshots")
    with op.batch_alter_table("ingestion_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_records_run_id"))

    op.drop_table("ingestion_records")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_identity_hash"))
        batch_op.drop_index(batch_op.f("ix_contacts_company_id"))

    op.drop_table("contacts")
    op.drop_table("ingestion_runs")
    op.drop_table("duplicate_candidates")
    with op.batch_alter_table("company_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_identifiers_company_id"))

    op.drop_table("company_identifiers")
    op.drop_table("sources")
    op.drop_table("contact_suppressions")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_sector"))
        batch_op.drop_index(batch_op.f("ix_companies_review_status"))
        batch_op.drop_index(batch_op.f("ix_companies_qualification_status"))
        batch_op.drop_index(batch_op.f("ix_companies_normalized_name"))
        batch_op.drop_index(batch_op.f("ix_companies_country"))

    op.drop_table("companies")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_company_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
