"""company financials and registered addresses

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_financials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("revenue", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("ebitda", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("net_income", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("dividends", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("capex", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("depreciation", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("depreciation_and_impairment", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("operating_profit", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("profit_before_tax", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("total_assets", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("equity", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("labour_cost", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("employees_fte", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_file", sa.String(length=300), nullable=True),
        sa.Column("snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("usage_policy", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("statement_scope", sa.String(length=16), nullable=True),
        sa.Column("value_type", sa.String(length=16), nullable=False),
        sa.Column("filing_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("restated", sa.Boolean(), nullable=True),
        sa.Column("calculation_formula", sa.Text(), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("registry_code", sa.String(length=32), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "source_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["source_snapshots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_key", "content_hash", name="uq_financial_source_version"),
    )
    with op.batch_alter_table("company_financials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_company_financials_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_company_financials_fiscal_year"), ["fiscal_year"], unique=False)
        batch_op.create_index("ix_financial_company_year", ["company_id", "fiscal_year"], unique=False)
        batch_op.create_index("ix_financial_source_key", ["source_id", "source_key"], unique=False)

    op.create_table(
        "registered_addresses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("address_line", sa.String(length=300), nullable=True),
        sa.Column("postal_code", sa.String(length=16), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("municipality", sa.String(length=120), nullable=True),
        sa.Column("county", sa.String(length=120), nullable=True),
        sa.Column("ehak_code", sa.String(length=8), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_file", sa.String(length=300), nullable=True),
        sa.Column("snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("valid_from", app.models.UTCDateTime(), nullable=False),
        sa.Column("valid_to", app.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["source_snapshots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "source_id", "content_hash", name="uq_registered_address_version"),
    )
    with op.batch_alter_table("registered_addresses", schema=None) as batch_op:
        batch_op.create_index("ix_registered_address_current", ["company_id", "valid_to"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registered_addresses", schema=None) as batch_op:
        batch_op.drop_index("ix_registered_address_current")

    op.drop_table("registered_addresses")
    with op.batch_alter_table("company_financials", schema=None) as batch_op:
        batch_op.drop_index("ix_financial_source_key")
        batch_op.drop_index("ix_financial_company_year")
        batch_op.drop_index(batch_op.f("ix_company_financials_fiscal_year"))
        batch_op.drop_index(batch_op.f("ix_company_financials_company_id"))

    op.drop_table("company_financials")
    # ### end Alembic commands ###
