"""company share capital and shareholders

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models  # noqa: F401

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_shareholders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("holder_type", sa.String(length=16), nullable=False),
        sa.Column("holder_name", sa.String(length=300), nullable=False),
        sa.Column("holder_registry_code", sa.String(length=32), nullable=True),
        sa.Column("holder_country", sa.String(length=8), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("holding_amount", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("holding_currency", sa.String(length=3), nullable=True),
        sa.Column("holding_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("holding_type", sa.String(length=64), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_file", sa.String(length=300), nullable=True),
        sa.Column("snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("observed_at", app.models.UTCDateTime(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("valid_from", app.models.UTCDateTime(), nullable=False),
        sa.Column("valid_to", app.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["source_snapshots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_shareholders", schema=None) as batch_op:
        batch_op.create_index("ix_company_shareholder_current", ["company_id", "valid_to"], unique=False)
        batch_op.create_index(
            "ix_company_shareholder_hash", ["company_id", "source_id", "content_hash"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_shareholders", schema=None) as batch_op:
        batch_op.drop_index("ix_company_shareholder_hash")
        batch_op.drop_index("ix_company_shareholder_current")

    op.drop_table("company_shareholders")
    # ### end Alembic commands ###
